### PR TITLE
Allow custom icons to be rendered with a function

### PR DESCRIPTION
**Pull request by nguyenchr**
lets you do the following for custom icons

```jsx
import Icon from 'react-native-vector-icons/FontAwesome'
import { RichTextToolbar, actions } from 'react-native-zss-rich-text-editor'

<RichTextToolbar
  getEditor={() => this.richtext}
  actions={[
    actions.setBold,
    actions.setItalic,
    actions.setUnderline
  ]}
  iconMap={{
    [actions.setBold]: () => (<Icon name='bold' size={20} color='grey'/>),
    [actions.setItalic]: () => (<Icon name='italic' size={20} color='grey'/>),
    [actions.setUnderline]: () => (<Icon name='underline' size={20} color='grey'/>)
  }}
/>

```

### CODE REVIEW

**Comment by nguyenchr** [comment]
closing due to inactivity

**Comment by udarts** [comment]
Please pull this commit into the master. So we can choose whether we use icons or images for the toolbar.

**Comment by pgonzalez-santiago** [comment]
Why did you closed this pull request?

**Comment by JeremyBradshaw7** [comment]
I could also do with this enhancement - please consider reopening and merging.

**Comment by babitakapoor112** [comment]
How do I add more actions like underline and others in the toolbar

**Pull request closed without merging**
